### ISSUE TITLE
redis-lru don't support ioredis

### ISSUE THREAD

**Issue by dearpeach** [facundoolano/redis-lru#12] opened 2019-01-23 03:48 UTC
Here is my code: 
`const lru = require('redis-lru');

var Redis = require('ioredis');
const redis = new Redis();
const personCache = lru(redis, {
    max: 100000,
    namespace: 'test',
    maxAge: 24 * 60 * 60 * 1000, // 1 day
});

personCache.get('john').then(console.log)`

And then, the result is:
`(node:44421) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token , in JSON at position 0
    at JSON.parse (<anonymous>)
    at asPromise.then (/Users/zengtao/Documents/demo/test/node_modules/redis-lru/index.js:83:21)
    at <anonymous>
(node:44421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Please help me to find the problem, thanks a lot~

**Comment by dearpeach** [comment] 2019-01-23 04:10
I see, It's a bug when use ioredis to get the cache, it will throw an error when parse json.

**Comment by dearpeach** [comment] 2019-01-23 04:51
The error is at index.js -> 83 line.
when use "redis" module, the result is [value, 1], so it's ok to use 'redis' module;
but when use 'ioredis' module, the result is [[null, value], [null, 1]], the result[0] is an array, so it will throw an error.

**Comment by dearpeach** [comment] 2019-01-24 08:30
Can you give me a permission , I want to commit a PR.
@facundoolano

**Comment by facundoolano** [comment] 2019-01-24 12:55
You don't need any permission, just fork and propose a PR.

**Comment by dearpeach** [comment] 2019-01-25 03:09
> You don't need any permission, just fork and propose a PR.

done

**Comment by facundoolano** [comment] 2019-02-20 15:11
duplicate of #9

**Closed as completed by facundoolano** 2019-02-20 15:11 UTC
